locale                   : "en-US"
title                    : "Resume"
title_separator          : "-"
name                     : "Mark Filatov"
description              : "Resume"
teaser                   : "/assets/images/mark46.png"
logo                     : "/assets/images/88x88.png"
encoding                 : "utf-8"
theme                    : minima
minima:
  skin: dark
header_pages:
  - /
  - /resume
author:
  name: "MARK-46"
  email: "mark.38.98.ii@gmail.com"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
