remote_theme             : mmistakes/minimal-mistakes
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale                   : "en-US"
title                    : "Resume"
title_separator          : "-"
name                     : "Mark Filatov"
description              : "Resume"
teaser                   : "/assets/images/mark46.png"
logo                     : "/assets/images/88x88.png"
encoding                 : "utf-8"

author:
  name                   : "MARK-46"
  avatar                 : "/assets/images/mark46.png"
  bio                    : "Developer"
  email                  : 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mark.38.98.ii@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MARK-46"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/MARK_046"
    - label: "VK"
      icon: "fab fa-fw fa-vk"
      url: "https://t.me/MARK_046"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
